# Modèle linéaire

Considérons la cas classique d'une fonction affine :

$$y=ax+b$$

Ici, $a$ et $b$ sont des réels. Ces deux nombres définissent entièrement la courbe et permet donc d'obtenir une relation **affine** entre $x$ et $y$. En statistique, cette relation est à la base des modèles dit **linéaires**, où une variable réponse se définit comme une somme de variables explicatives où chacune de ces dernières sont multipliés par un coefficient.


## Modèle linéaire simple

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Linear_regression.svg/438px-Linear_regression.svg.png)

Dans le modèle linéaire simple (une seule variable explicative), on suppose que la variable réponse suit le modèle suivant :

$$y_i=\beta_0 + \beta_1 x_i + \varepsilon_i$$

On remarque la ressemblance avec la fonction affine présentée ci-dessus. La différence réside dans l'existence du terme aléatoire (appelé bruit) $\varepsilon_i$. Afin de considérer le modèle, il est nécessaire de se placer sous les hypothèses suivantes

$$(\mathcal{H}) : \left\{\begin{matrix}
\mathbb{E}[\varepsilon_i]=0\\ 
\text{Cov}(\varepsilon_i, \varepsilon_j)=\delta_{ij} \sigma^2
\end{matrix}\right.$$
Les différents éléments qui interviennent sont :

- $\beta_0$ : l'ordonnée à l'origine (nommée *intercept*)
- $\beta_1$ : le coefficient directeur
- $x_i$ : l'observation $i$
- $y_i$ : le $i$-ème prix
- $\varepsilon_i$ : le bruit aléatoire liée à la $i$-ème observation

La solution peut se calculer facilement via les formules fermées suivantes :

$$\hat{\beta}_1=\frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2} \qquad \hat{\beta}_0 = \hat{y} - \hat{\beta}_1 \bar{x}$$

## Modèle linéaire multiple

Dans le cas multiple (pour $p$ variables explicatives), pour la $i$-ème observation, le modèle s'écrit :

$$y_i= \beta_0 + \sum_{j=1}^p \beta_j x_{ij} + \varepsilon_i$$

Ainsi, une observation $x_i$ n'est plus une valeur, mais un **vecteur** $(x_{i1}, \dots, x_{ip})$. Il est plus commode de regrouper ces prix $y_i$ et ces vecteurs d'observations $x_i$ dans des matrices :

$$Y=X \beta + \varepsilon$$

Sous les hypothèses équivalentes du modèle simple en plus grand dimension

$$(\mathcal{H}) : \left\{\begin{matrix}
\text{rank}(X)=p\\ 
\mathbb{E}[\varepsilon]=0 \text{ et }\text{Var}(\varepsilon)=\sigma^2 I_p
\end{matrix}\right.$$

Les différents éléments qui interviennent sont :

- $\beta$ : le vecteur directeur
- $X$ : la matrice des observations
- $Y$ : le vecteur de prix
- $\varepsilon$ : le vecteur de bruit

Avec $X=( \mathbf{1}, X_1, \dots, X_n)$, $Y=(y_1, \dots, y_n)^\top$ et $\varepsilon=(\varepsilon_1, \dots, \varepsilon_n)^\top$. La solution des MCO (Moindres Carrés Ordinaires) est alors :

$$\hat{\beta}= (X^\top X)^{-1} X^\top Y$$

Vous pouvez d'ailleurs faire la démonstration de votre coté ! Pour plus d'information mathématiques, je vous conseil le portail de wikipédia qui est très bien fait : [lien ici](https://fr.wikipedia.org/wiki/Portail:Probabilit%C3%A9s_et_statistiques)

# Implémenter une régression linéaire

In [24]:
#importer vos librairies 
import pandas as pd 
import numpy as np 
import seaborn as s
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

In [11]:
#charger les données 
#price_availability.csv
df=pd.read_csv(r'C:\Users\u164539\doodle\cheers2019\data\price_availability.csv',sep=';')
df.info()
#listings_final.csv
dl=pd.read_csv(r'C:\Users\u164539\doodle\cheers2019\data\listings_final.csv',sep=';')
#attention aux valeurs manquantes !!
dl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4748696 entries, 0 to 4748695
Data columns (total 7 columns):
listing_id        int64
day               object
created           object
available         bool
local_currency    object
local_price       int64
min_nights        int64
dtypes: bool(1), int64(3), object(3)
memory usage: 221.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
Unnamed: 0                  1000 non-null int64
listing_id                  1000 non-null int64
name                        1000 non-null object
type                        1000 non-null object
city                        1000 non-null object
neighborhood                935 non-null object
latitude                    1000 non-null float64
longitude                   1000 non-null float64
person_capacity             1000 non-null int64
beds                        1000 non-null int64
bedrooms                    1000 non-null int64
bathrooms                   1000 non-null float64
is_rebookable               1000 non-null bool
is_new_listing              1000 non-null bool
is_fully_refundable         1000 non-null bool
is_host_highly_rated        1000 non-null bool
is_business_travel_ready    1000 non-null bool
pricing_weekly_factor       1000 non-null float64
pricing_monthly_factor      1000 non-null float64
dtypes: bool(5), float64(5), int64(5), object(4)
memory usage: 114.4+ KB

In [15]:
df = df.groupby("listing_id").mean()
dfinal = pd.merge(df,dl, on = 'listing_id')
dfinal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 998
Data columns (total 22 columns):
listing_id                  999 non-null int64
available                   999 non-null float64
local_price                 999 non-null float64
min_nights                  999 non-null float64
Unnamed: 0                  999 non-null int64
name                        999 non-null object
type                        999 non-null object
city                        999 non-null object
neighborhood                934 non-null object
latitude                    999 non-null float64
longitude                   999 non-null float64
person_capacity             999 non-null int64
beds                        999 non-null int64
bedrooms                    999 non-null int64
bathrooms                   999 non-null float64
is_rebookable               999 non-null bool
is_new_listing              999 non-null bool
is_fully_refundable         999 non-null bool
is_host_highly_rated        999 non-null bool
is_business_travel_ready    999 non-null bool
pricing_weekly_factor       999 non-null float64
pricing_monthly_factor      999 non-null float64
dtypes: bool(5), float64(8), int64(5), object(4)
memory usage: 145.4+ KB

## Données d'entrée

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11749 entries, 5396 to 28851976
Data columns (total 3 columns):
available      11749 non-null float64
local_price    11749 non-null float64
min_nights     11749 non-null float64
dtypes: float64(3)
memory usage: 367.2 KB

L'objectif ici est de charger les données pour créer les matrices $X$ et $Y$ du modèle linéaire. **Attention**, il n'est pas nécessaire de rajouter le vecteur colonne $\mathbf{1}$ en première colonne, car *scikit-learn* le fait automatiquement !

In [29]:
listing = dl.groupby('listing_id').mean()
listing

,Unnamed: 0,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
listing_id,,,,,,,,,,,,,,
56093,12,48.867284,2.358431,4,2,1,1.0,False,False,True,True,False,0.88,1.0
57207,13,48.846184,2.304455,2,1,1,1.0,False,False,True,False,False,0.87,1.0
114543,19,48.849530,2.290219,2,1,1,1.0,False,False,True,True,False,0.90,0.9
149534,9,48.866360,2.361844,4,2,1,1.0,False,False,True,True,False,1.00,0.4
164255,28,48.861398,2.364299,4,2,1,1.0,False,False,True,False,False,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28684174,662,48.879223,2.292382,5,0,1,1.0,False,True,True,False,False,1.00,1.0
28709644,745,48.872202,2.298349,4,2,1,1.0,False,True,True,False,False,1.00,1.0
28751412,88,48.880923,2.314568,2,1,0,1.0,False,True,True,False,False,1.00,1.0
28774896,159,48.852915,2.314519,2,1,1,1.0,False,True,True,False,False,1.00,1.0
28792796,998,48.870109,2.321475,6,4,2,1.5,False,True,True,False,False,1.00,1.0

In [34]:
#définir vos variables de travail X et Y
X = np.array(f[['person_capacity', 'bedrooms', 'bathrooms']])
Y = np.array(f[['local_price']])
Y
X

array([[4. , 1. , 1. ],
       [2. , 1. , 1. ],
       [2. , 1. , 1. ],
       ...,
       [2. , 0. , 1. ],
       [2. , 1. , 1. ],
       [6. , 2. , 1.5]])

In [61]:
#construire l'array des prix
prix = df.groupby(['listing_id']).mean()
prix

            available  local_price  min_nights
listing_id
5396         0.011494   102.363985    2.000000
7397         0.168297   110.107632   11.000000
9342         0.309198   396.863014    2.784736
10010        0.254593   136.154856    4.955381
10270        0.511688   105.779221    4.937662
...               ...          ...         ...
28836096     0.082707   321.428571    1.022556
28838519     0.083333    54.483333    5.000000
28840013     0.743083   112.122530    2.000000
28846494     0.225564   168.037594    4.000000
28851976     0.812030   128.000000    2.000000

[11749 rows x 3 columns]

In [63]:
f = pd.merge(prix[['local_price']], listing, on=['listing_id'])
f

,local_price,Unnamed: 0,latitude,longitude,person_capacity,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
listing_id,,,,,,,,,,,,,,,
56093,170.000000,12,48.867284,2.358431,4,2,1,1.0,False,False,True,True,False,0.88,1.0
57207,49.952756,13,48.846184,2.304455,2,1,1,1.0,False,False,True,False,False,0.87,1.0
114543,107.374026,19,48.849530,2.290219,2,1,1,1.0,False,False,True,True,False,0.90,0.9
149534,169.000000,9,48.866360,2.361844,4,2,1,1.0,False,False,True,True,False,1.00,0.4
164255,75.876209,28,48.861398,2.364299,4,2,1,1.0,False,False,True,False,False,1.00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28684174,725.175781,662,48.879223,2.292382,5,0,1,1.0,False,True,True,False,False,1.00,1.0
28709644,475.000000,745,48.872202,2.298349,4,2,1,1.0,False,True,True,False,False,1.00,1.0
28751412,117.000000,88,48.880923,2.314568,2,1,0,1.0,False,True,True,False,False,1.00,1.0
28774896,156.397468,159,48.852915,2.314519,2,1,1,1.0,False,True,True,False,False,1.00,1.0
28792796,49.184211,998,48.870109,2.321475,6,4,2,1.5,False,True,True,False,False,1.00,1.0

En *Machine Learning*, on a l'habitude de couper l'ensemble de données en deux sous-ensembles :

- Un ensemble d'entraînement (*train set*), sur lequel le modèle va être calibré.
- Un ensemble de test (*test set*), qui ne sera pas utilisé pendant le calibrage mais permettra de vérifier l'aptitude du modèle à généraliser sur de nouvelles observations inconnues.

En général, on découpe l'ensemble de données (*split*) en prenant $\alpha \%$ de l'ensemble pour entraînement et $1-\alpha \%$ comme test. Dans la plus part des cas, on considère que $\alpha=10,20\ ou \ 30\%$.

In [44]:
#utiliser la méthode split de sklearn en splitant avec un alpha=30 et un random state=42 
#afficher la shape de vos données 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=42)
Y_test

array([[  43.14368932],
       [1300.        ],
       [  57.88653846],
       [ 297.76315789],
       [  55.34933333],
       [ 600.        ],
       [  28.4947644 ],
       [  17.9766537 ],
       [  79.81038961],
       [ 250.19379845],
       [ 221.99738903],
       [ 114.95833333],
       [ 350.        ],
       [ 170.        ],
       [ 195.        ],
       [ 166.328125  ],
       [ 340.81007752],
       [  93.18393782],
       [ 160.02645503],
       [ 203.41755319],
       [ 146.57519789],
       [ 149.        ],
       [ 329.36832061],
       [ 182.30769231],
       [ 299.        ],
       [ 240.        ],
       [ 108.        ],
       [ 118.78473581],
       [ 250.        ],
       [  47.59585492],
       [ 126.32198953],
       [ 184.30628272],
       [  93.35248042],
       [ 176.37075718],
       [  59.        ],
       [ 148.76804124],
       [  30.        ],
       [ 425.        ],
       [ 226.89210526],
       [  71.01804124],
       [ 204.6342711 ],
       [  79.        ],
       [ 124.45052083],
       [ 250.05483029],
       [  92.        ],
       [  42.        ],
       [  88.98966408],
       [  86.80687831],
       [  61.10909091],
       [  99.45801527],
       [ 242.21052632],
       [  62.13533835],
       [ 259.2578125 ],
       [ 154.65384615],
       [ 163.47286822],
       [ 203.89312977],
       [  60.74093264],
       [  47.84031414],
       [ 350.88565891],
       [ 670.        ],
       [ 172.67822736],
       [ 151.39790576],
       [ 121.46456693],
       [  30.        ],
       [ 134.20424403],
       [ 159.933687  ],
       [ 116.09947644],
       [ 145.        ],
       [ 195.72890026],
       [ 650.        ],
       [  60.65091864],
       [ 258.2767624 ],
       [ 153.63116883],
       [ 270.        ],
       [  59.        ],
       [  40.46391753],
       [ 234.89460154],
       [  76.98153034],
       [ 161.5503876 ],
       [ 183.68085106],
       [  62.3908046 ],
       [ 290.        ],
       [ 145.67829457],
       [ 360.        ],
       [ 447.31538462],
       [ 281.56657963],
       [ 252.3126615 ],
       [  82.23643411],
       [ 195.        ],
       [ 683.94584139],
       [ 221.41015625],
       [ 234.14038462],
       [ 181.24870466],
       [  40.        ],
       [ 102.31151832],
       [ 245.        ],
       [ 226.        ],
       [ 617.13541667],
       [ 139.95844156],
       [ 103.56103896],
       [ 374.62273902],
       [ 208.        ],
       [  48.        ],
       [ 240.        ],
       [ 409.        ],
       [  88.38947368],
       [ 125.        ],
       [ 140.50895141],
       [ 321.00795756],
       [  42.61658031],
       [ 420.46456693],
       [ 170.64935065],
       [  69.01550388],
       [  52.        ],
       [  20.        ],
       [ 459.71391076],
       [ 135.85677083],
       [  49.60159363],
       [ 297.        ],
       [ 264.83558994],
       [ 510.07751938],
       [  53.50129199],
       [  75.37105263],
       [  32.71948052],
       [  50.50642674],
       [  59.        ],
       [ 104.        ],
       [ 152.53299492],
       [ 255.87548638],
       [  25.        ],
       [  35.        ],
       [ 725.17578125],
       [ 168.91395793],
       [ 109.        ],
       [ 144.        ],
       [ 184.31168831],
       [  44.16569201],
       [ 199.42746114],
       [  53.        ],
       [ 170.        ],
       [ 153.3203125 ],
       [ 250.        ],
       [ 718.09278351],
       [ 417.80392157],
       [ 250.        ],
       [ 188.57253886],
       [ 794.54663212],
       [ 433.40535373],
       [ 195.        ],
       [  39.14750958],
       [ 163.60103627],
       [  81.80851064],
       [  98.35695538],
       [ 135.11227154],
       [  98.        ],
       [ 990.        ],
       [  70.30989583],
       [  52.        ],
       [ 177.52645503],
       [  33.03645833],
       [ 154.97927461],
       [  35.40932642],
       [ 170.        ],
       [ 330.46875   ],
       [ 326.99232246],
       [ 143.51181102],
       [ 300.        ],
       [ 220.        ],
       [ 136.62597403],
       [ 155.        ],
       [  38.51171875],
       [ 170.00793651],
       [ 274.10485437],
       [  36.72093023],
       [  93.46475196],
       [ 527.13867188],
       [ 179.54263566],
       [  56.28871391],
       [ 183.01151631],
       [1000.        ],
       [ 152.25773196],
       [  43.58115183],
       [ 931.65535248],
       [  47.80577428],
       [ 309.9034749 ],
       [  93.57142857],
       [ 309.68911917],
       [ 158.84473684],
       [  68.35142119],
       [ 204.95064935],
       [ 196.58854167],
       [ 421.97260274],
       [ 180.        ],
       [ 403.08070866],
       [ 347.29166667],
       [  59.        ],
       [ 105.        ],
       [ 328.57699805],
       [ 230.        ],
       [  79.97668394],
       [ 806.90909091],
       [ 149.        ],
       [  68.        ],
       [  35.03116883],
       [  40.06753247],
       [ 450.        ],
       [ 357.44125326],
       [ 132.36363636],
       [  79.        ],
       [ 161.83116883],
       [ 176.86125654],
       [ 306.8477842 ],
       [ 219.5037594 ],
       [ 119.34816754],
       [  62.17525773],
       [  99.        ],
       [ 198.79533679],
       [ 161.59689922],
       [ 158.        ],
       [ 179.67315175],
       [ 650.        ],
       [  54.10433071],
       [  32.06266319],
       [ 122.58461538],
       [  30.08488064],
       [ 900.        ],
       [ 257.89556136],
       [ 115.        ],
       [  41.11340206],
       [  99.91076115],
       [ 128.8630491 ],
       [ 190.        ],
       [ 232.38921002],
       [ 119.28759894],
       [  63.14397906],
       [ 137.21204188],
       [ 169.        ],
       [ 109.        ],
       [ 386.57751938],
       [ 186.17829457],
       [  33.53050398],
       [  92.        ],
       [  79.84126984],
       [ 371.36363636],
       [ 277.        ],
       [  43.01578947],
       [  86.        ],
       [ 130.        ],
       [  39.92307692],
       [ 375.0268714 ],
       [  52.89126214],
       [  60.02610966],
       [  65.675     ],
       [  58.72386059],
       [ 107.37402597],
       [ 184.55208333],
       [ 220.        ],
       [ 311.54580153],
       [ 284.35356201],
       [  46.87012987],
       [ 490.61662198],
       [ 380.        ],
       [ 181.04986877],
       [  89.        ],
       [ 834.61121857],
       [ 124.7591623 ],
       [ 390.16184971],
       [ 179.21336761],
       [  42.10471204],
       [ 115.        ],
       [  76.        ],
       [ 650.87596899],
       [ 327.96711799],
       [  70.40310078],
       [  67.20833333],
       [ 129.38481675],
       [ 145.16966581],
       [ 220.        ],
       [ 164.52196382],
       [ 184.40789474],
       [ 117.        ],
       [ 290.        ],
       [  29.        ],
       [  69.27447217],
       [ 156.24031008],
       [  89.        ],
       [  40.        ],
       [ 400.39787798],
       [  82.90526316],
       [  97.18372703],
       [ 357.7046332 ],
       [  59.16020672],
       [  35.11111111],
       [ 152.56701031],
       [ 147.75255102],
       [ 195.        ],
       [ 109.        ],
       [ 300.        ],
       [  68.16358839],
       [  73.78249337]])

In [45]:
Y_test.shape

(300, 1)

In [46]:
Y_train.shape

(699, 1)

In [47]:
X_test.shape

(300, 3)

In [48]:
X_train.shape

(699, 3)

## Entraînement

Pour information, *scikit-learn* utilise le solveur OLS (Ordinary Least Squares) de *numpy*.

In [51]:
#créer l'objet de régression et entrainer le sur notre ensemble d'entraînement
reg = linear_model.LinearRegression().fit(X_train, Y_train)
reg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

On affiche le vecteur des coefficients pour interpréter rapidement le modèle.

In [60]:
#afficher les coefficients
print("Coefficient beta_j :\n {} \n Coefficient INTERCEPT beta_0 :\n {}".format(reg.coef_,reg.intercept_))
#que remarquez vous ? 
#la data qui est plus importance c'est laquelle qui est lier au bathroom

Coefficient beta_j :
 [[29.22157692 14.61898054 86.34152526]]
 Coefficient INTERCEPT beta_0 :
 [-46.48417235]

## Validation du modèle

### Le coefficient de détermination $R^2$

Par la suite, nous ferons l'hypothèse de gaussianité sur les bruits. Dans l'idée, nous aimerions obtenir une valeur numérique qui nous indique à quel point la régression linéaire a un sens sur nos données. Pour cela, introduisons les notations suivantes :

- $SCT=\|Y-\hat{y} \mathbf{1}\|^2$ est la somme des carrés totaux
- $SCE=\|\hat{Y}-\hat{y} \mathbf{1}\|^2$ est la somme des carrés expliqués
- $SCR=\|\hat{\varepsilon}\|^2$ est la somme des carrés résiduels

L'idée est de décomposer la somme des carrés totaux comme la somme des carrés que le modèle explique, en plus de la somme des carrés qui sont liés aux résidus (et donc que le modèle ne peut pas expliquer). On voit donc ici l'intérêt de calculer un coefficient à partir du $SCE$. Puisque l'on a la relation suivante :

$$SCT=SCE+SCR \text{ alors } 1=\frac{SCE}{SCT}+\frac{SCR}{SCT}$$

Plus les résidus sont petits (et donc la régression est "bonne"), plus $SCR$ devient petit et donc $SCE$ devient grand. Le schéma inverse s'opère de la même façon. Dans le meilleur des cas, on obtient $SCR=0$ et donc $SCE=SCT$ d'où le premier membre vaut $1$. Dans le cas contraite, $SCE=0$ et automatiquement, le premier membre est nul. C'est ainsi que l'on définit le coefficient de détermination $R^2$ comme 
$$R^2=\frac{SCE}{SCT}=1-\frac{SCR}{SCT}$$
Ainsi, $R^2 \in [0,1]$. Plus $R^2$ est proche de $1$, plus la régression linéaire a du sens. Au contraire, si $R^2$ est proche de $0$, le modèle linéaire possède un faible pouvoir explicatif.

In [53]:
#faire une prediction sur X
Y_pred = reg.predict(X_test)
Y_pred

array([[126.868673  ],
       [534.01051785],
       [112.91948729],
       [215.20319858],
       [ 98.30050675],
       [345.3852813 ],
       [112.91948729],
       [ 83.69791037],
       [112.91948729],
       [518.73812664],
       [185.98162166],
       [ 98.30050675],
       [316.16370438],
       [171.36264112],
       [156.09024991],
       [244.4247755 ],
       [185.98162166],
       [171.36264112],
       [316.16370438],
       [214.53340375],
       [112.91948729],
       [112.91948729],
       [433.70342272],
       [112.91948729],
       [112.91948729],
       [330.76630076],
       [171.36264112],
       [ 98.30050675],
       [156.74366058],
       [112.91948729],
       [ 98.30050675],
       [142.1410642 ],
       [156.74366058],
       [259.04375604],
       [ 98.30050675],
       [171.36264112],
       [112.91948729],
       [272.32314692],
       [330.76630076],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [214.53340375],
       [388.55604393],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [112.91948729],
       [142.1410642 ],
       [112.91948729],
       [214.53340375],
       [142.1410642 ],
       [215.20319858],
       [243.10157   ],
       [171.36264112],
       [374.60685822],
       [142.1410642 ],
       [112.91948729],
       [506.7655571 ],
       [345.3852813 ],
       [244.4247755 ],
       [112.91948729],
       [432.39660139],
       [ 69.07892983],
       [330.76630076],
       [244.4247755 ],
       [142.1410642 ],
       [112.91948729],
       [215.20319858],
       [185.98162166],
       [112.91948729],
       [403.82843513],
       [272.32314692],
       [185.98162166],
       [112.91948729],
       [ 55.79953895],
       [258.37396121],
       [112.91948729],
       [200.58421804],
       [156.09024991],
       [142.1410642 ],
       [345.3852813 ],
       [215.20319858],
       [520.06133214],
       [403.82843513],
       [185.98162166],
       [229.15238429],
       [112.91948729],
       [185.98162166],
       [272.32314692],
       [330.76630076],
       [215.20319858],
       [112.91948729],
       [ 98.30050675],
       [112.91948729],
       [142.1410642 ],
       [272.32314692],
       [185.98162166],
       [142.1410642 ],
       [ 98.30050675],
       [142.1410642 ],
       [171.36264112],
       [ 98.30050675],
       [ 98.30050675],
       [330.76630076],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [112.91948729],
       [112.91948729],
       [112.91948729],
       [171.36264112],
       [ 83.69791037],
       [142.1410642 ],
       [ 40.52714774],
       [171.36264112],
       [185.98162166],
       [ 83.69791037],
       [272.32314692],
       [215.20319858],
       [548.62949839],
       [ 98.30050675],
       [112.91948729],
       [ 83.69791037],
       [ 98.30050675],
       [112.91948729],
       [ 98.30050675],
       [286.9257433 ],
       [112.91948729],
       [ 83.69791037],
       [112.91948729],
       [200.58421804],
       [171.36264112],
       [171.36264112],
       [ 98.30050675],
       [244.4247755 ],
       [112.91948729],
       [462.28797314],
       [112.91948729],
       [185.98162166],
       [112.91948729],
       [272.32314692],
       [446.99919776],
       [535.33372335],
       [200.58421804],
       [ 83.69791037],
       [474.89756918],
       [171.36264112],
       [229.15238429],
       [112.91948729],
       [244.4247755 ],
       [213.87999308],
       [171.36264112],
       [142.1410642 ],
       [244.4247755 ],
       [634.30122882],
       [112.91948729],
       [156.74366058],
       [142.1410642 ],
       [ 98.30050675],
       [244.4247755 ],
       [112.91948729],
       [142.1410642 ],
       [171.36264112],
       [185.98162166],
       [156.74366058],
       [ 98.30050675],
       [244.4247755 ],
       [ 98.30050675],
       [171.36264112],
       [ 98.30050675],
       [185.98162166],
       [243.75498067],
       [ 98.30050675],
       [156.09024991],
       [315.49390955],
       [345.3852813 ],
       [ 69.07892983],
       [447.66899259],
       [406.45846196],
       [ 98.30050675],
       [ 25.9081672 ],
       [171.36264112],
       [112.91948729],
       [462.27158897],
       [112.91948729],
       [272.32314692],
       [171.36264112],
       [127.52208366],
       [273.64635242],
       [330.76630076],
       [112.91948729],
       [112.91948729],
       [474.89756918],
       [257.70416638],
       [142.1410642 ],
       [185.98162166],
       [330.76630076],
       [273.66273658],
       [112.91948729],
       [345.3852813 ],
       [112.91948729],
       [112.91948729],
       [142.1410642 ],
       [112.91948729],
       [345.3852813 ],
       [171.36264112],
       [ 98.30050675],
       [171.36264112],
       [ 98.30050675],
       [112.91948729],
       [330.76630076],
       [259.04375604],
       [142.1410642 ],
       [142.1410642 ],
       [185.98162166],
       [112.91948729],
       [199.93080737],
       [112.91948729],
       [112.91948729],
       [272.32314692],
       [142.1410642 ],
       [112.91948729],
       [156.74366058],
       [ 83.69791037],
       [215.20319858],
       [112.91948729],
       [156.74366058],
       [112.91948729],
       [171.36264112],
       [112.91948729],
       [200.58421804],
       [112.91948729],
       [112.91948729],
       [ 98.30050675],
       [215.18681442],
       [171.36264112],
       [171.36264112],
       [460.94838347],
       [215.20319858],
       [112.91948729],
       [185.98162166],
       [112.91948729],
       [127.53846783],
       [171.36264112],
       [ 83.69791037],
       [171.36264112],
       [ 98.30050675],
       [112.91948729],
       [419.10082634],
       [127.52208366],
       [171.36264112],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [156.09024991],
       [244.4247755 ],
       [301.54472384],
       [185.98162166],
       [112.91948729],
       [447.65260843],
       [345.3852813 ],
       [288.26533296],
       [ 98.30050675],
       [373.93706338],
       [112.91948729],
       [185.98162166],
       [215.20319858],
       [ 40.52714774],
       [185.98162166],
       [185.98162166],
       [185.98162166],
       [316.16370438],
       [ 98.30050675],
       [112.91948729],
       [112.91948729],
       [142.1410642 ],
       [418.44741568],
       [171.36264112],
       [229.82217912],
       [215.20319858],
       [229.15238429],
       [ 83.69791037],
       [112.91948729],
       [171.36264112],
       [171.36264112],
       [112.91948729],
       [259.04375604],
       [112.91948729],
       [171.36264112],
       [447.65260843],
       [112.91948729],
       [112.91948729],
       [171.36264112],
       [142.1410642 ],
       [287.59553813],
       [ 98.30050675],
       [142.1410642 ],
       [112.91948729],
       [ 98.30050675]])

In [58]:
#afficher l'erreur des moindres carrées sur l'ensemble d'entrainement ainsi que le R2
e=mean_squared_error(Y_test, Y_pred)
e

21600.006742647594

In [57]:
R=r2_score(Y_test, Y_pred)
R

0.3772870887592449

In [ ]:
#que remarquez vous ? 
# R^2<0.70 alors le modèle linéaire possède un faible pouvoir explicatif.